import './utils/styles/globals.css'
import { Nunito } from 'next/font/google'
import { ReactNode } from 'react'
import Main from '@/app/main'

const font = Nunito({
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en'>
			<body className={font.className}>
			{/* eslint-disable-next-line react/no-children-prop */}
				<Main children={children} />
			</body>
		</html>
	)
}
